version: '3.8'

networks:
  pharm-vision:

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - pharm-vision

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file:
      - .frontend.env
    ports:
      - '3000:3000'
    networks:
      - pharm-vision

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - .backend.env
    ports:
      - 4000:4000
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:prod"
    depends_on:
      - postgres
    restart: always
    networks:
      - pharm-vision

  backend-dev:
    container_name: backend-dev
    build:
      context: ./backend
    env_file:
      - .env.dev
    ports:
      - "4010:4000"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:prod"
    depends_on:
      - postgres
    restart: always
    networks:
      - pharm-vision

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - pharm-vision

volumes:
  pgdata: