user root;
worker_processes 1;

events {}

http {
    
    server {
        listen 80;
        listen 443 ssl;
        server_name xn----itbkgreg1a1b.xn--p1ai www.xn----itbkgreg1a1b.xn--p1ai;

        location /.well-known/acme-challenge/ { 
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        ssl_certificate /etc/letsencrypt/live/xn----itbkgreg1a1b.xn--p1ai/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xn----itbkgreg1a1b.xn--p1ai/privkey.pem;
    }

    server {
        listen 80;
        listen 443 ssl;
        server_name api.xn----itbkgreg1a1b.xn--p1ai www.api.xn----itbkgreg1a1b.xn--p1ai;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://backend:4000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /docs/ {
            proxy_pass http://backend:4000/docs/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /media/ {
            proxy_pass http://backend:4000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        ssl_certificate /etc/letsencrypt/live/xn----itbkgreg1a1b.xn--p1ai/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xn----itbkgreg1a1b.xn--p1ai/privkey.pem;
    }
}